FROM openjdk:17-alpine
ARG JAR_FILE
ARG PROJECT_PORT
ARG WORKING_DIRECTORY
VOLUME ${WORKING_DIRECTORY}
COPY ${JAR_FILE} ${WORKING_DIRECTORY}/application.jar
EXPOSE ${PROJECT_PORT}
WORKDIR ${WORKING_DIRECTORY}
ENTRYPOINT ["java", "-jar", "application.jar"]